[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_any_generics = True

[mypy-google.cloud.*]
ignore_missing_imports = True

[mypy-bleach.*]
ignore_missing_imports = True
