@echo off
echo Running Ruff...
ruff check . --select ALL > ruff_out2.txt
echo Running Mypy...
mypy . --strict > mypy_out2.txt
echo Running Bandit...
bandit -r . -ll -f json -o bandit_out2.json
echo Running Pytest...
pytest --cov=. --cov-report=term-missing > pytest_out2.txt
echo Done!
